# Generated by Django 2.2 on 2020-02-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliar', '0002_auto_20200206_0623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suppliar_Check_Order',
        ),
    ]
