# Generated by Django 2.2 on 2020-02-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0003_remove_shopping_cart_category'),
        ('suppliar', '0004_suppliar_check_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliar_check_order',
            name='factor',
        ),
        migrations.AddField(
            model_name='suppliar_check_order',
            name='factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.Shopping_Cart'),
        ),
    ]
