# Generated by Django 2.2 on 2020-02-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0003_remove_shopping_cart_category'),
        ('suppliar', '0005_auto_20200206_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliar_check_order',
            name='factor',
        ),
        migrations.AddField(
            model_name='suppliar_check_order',
            name='factor',
            field=models.ManyToManyField(to='shoppingCart.Shopping_Cart'),
        ),
    ]
