# Generated by Django 2.2 on 2020-03-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0003_remove_shopping_cart_category'),
        ('suppliar', '0006_auto_20200206_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliar_check_order',
            name='factor',
        ),
        migrations.AddField(
            model_name='suppliar_check_order',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.Shopping_Cart'),
        ),
    ]
