# Generated by Django 2.2 on 2020-04-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliar', '0008_auto_20200328_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliar_check_order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserInformation'),
        ),
    ]
