# Generated by Django 2.2 on 2020-02-04 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_baseitem_category'),
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='category',
            field=models.CharField(choices=[('Home Applience', 'Home Applience'), ('Digital Product', 'Digital Product')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.BaseItem'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='status',
            field=models.CharField(choices=[('on_cart', 'on_cart'), ('payed', 'payed')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
