# Generated by Django 2.2 on 2020-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0003_remove_shopping_cart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='status',
            field=models.CharField(choices=[('on_cart', 'on_cart'), ('ready_to_payed', 'ready_to_payed')], max_length=100, null=True),
        ),
    ]
