# Generated by Django 2.2 on 2020-02-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_userprofileadvance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileAdvance',
        ),
    ]
