# Generated by Django 2.2 on 2020-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20200328_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.ManyToManyField(related_name='informations', related_query_name='information', to='userProfile.UserInformation'),
        ),
    ]
