# Generated by Django 2.2 on 2020-03-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_auto_20200328_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='info',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
