# Generated by Django 2.2 on 2020-01-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.BaseItem')),
                ('color', models.CharField(max_length=100)),
                ('ram_Gig', models.SmallIntegerField()),
            ],
            bases=('content.baseitem',),
        ),
        migrations.CreateModel(
            name='HomeAppliance',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.BaseItem')),
                ('color', models.CharField(max_length=50)),
                ('weight', models.SmallIntegerField()),
            ],
            bases=('content.baseitem',),
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.BaseItem')),
                ('voltage', models.SmallIntegerField()),
                ('side_by_side', models.BooleanField()),
                ('top_mount_freezer', models.BooleanField()),
            ],
            bases=('content.baseitem',),
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.BaseItem')),
                ('resolution', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
            ],
            bases=('content.baseitem',),
        ),
        migrations.CreateModel(
            name='Laptob',
            fields=[
                ('digitalproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.DigitalProduct')),
                ('screen_size', models.CharField(max_length=100)),
                ('touch_screen_display', models.BooleanField()),
                ('graphics_card', models.BooleanField()),
            ],
            bases=('content.digitalproduct',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('digitalproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.DigitalProduct')),
                ('operation_system', models.CharField(choices=[('android', 'Android'), ('ios', 'IOS')], max_length=10)),
                ('display_resolution', models.CharField(max_length=100)),
                ('sim_card', models.CharField(choices=[('S', 'Standard'), ('M', 'Micro'), ('N', 'Nano')], max_length=3)),
            ],
            bases=('content.digitalproduct',),
        ),
    ]
