# Generated by Django 2.2 on 2020-01-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='brand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
