# Generated by Django 2.2 on 2020-01-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_baseitem_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrigerator',
            name='baseitem_ptr',
        ),
        migrations.RemoveField(
            model_name='television',
            name='baseitem_ptr',
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='homeappliance_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.HomeAppliance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='television',
            name='homeappliance_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.HomeAppliance'),
            preserve_default=False,
        ),
    ]
