# Generated by Django 2.2 on 2020-01-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200130_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
