# Generated by Django 2.2 on 2020-03-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200326_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazingOffer',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.BaseItem')),
            ],
            bases=('content.baseitem',),
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.BaseItem')),
            ],
            bases=('content.baseitem',),
        ),
    ]
