# Generated by Django 2.2 on 2020-03-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200326_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_detail', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.BaseItem')),
            ],
        ),
        migrations.CreateModel(
            name='AmazingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_detail', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.BaseItem')),
            ],
        ),
    ]
