# Generated by Django 2.2 on 2020-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_amazingoffer_topproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
