# Generated by Django 2.2 on 2020-03-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_baseitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
