# Generated by Django 2.2 on 2020-03-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200328_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseitem',
            name='slug',
        ),
    ]
