# Generated by Django 2.2 on 2020-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_baseitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='category',
            field=models.CharField(choices=[('Digital_Product', 'Digital_Product'), ('Home_Appliance', 'Home_Appliance'), ('Educational', 'Educational')], max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalproduct',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('silver', 'silver'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=100),
        ),
        migrations.AlterField(
            model_name='homeappliance',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('silver', 'silver'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('silver', 'silver'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=100),
        ),
    ]
