# Generated by Django 2.2 on 2020-03-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20200328_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyAddedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_detail', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.BaseItem')),
            ],
        ),
    ]
