# Generated by Django 2.2 on 2020-03-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_recentlyaddeditems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyAddedItems',
        ),
    ]
