# Generated by Django 2.2 on 2020-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_delete_recentlyaddeditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
